CC      = g++
CFLAGS  = -lm -Wall -std=c++11

SRC  = main.cpp
OUTPUT_DIR = ./dist
TARGET     := $(addprefix $(OUTPUT_DIR)/, $(notdir $(CURDIR)))

$(TARGET): main.cpp | $(OUTPUT_DIR)
	$(CC) $(CFLAGS) $? -o $@

run: $(TARGET)
	$(TARGET)

$(OUTPUT_DIR):
	mkdir -p $(OUTPUT_DIR)

clean:
	rm -rf $(OUTPUT_DIR)

judge: $(TARGET)
	judge readme.yaml $(TARGET)

watch:
	ls *.cpp *.yaml | entr -s 'make judge'

.PHONY: clean watch
